#!/bin/bash
# Released into the Public Domain, see the file 'unlicense.txt'
cpp_patch="96a97,113
> __CTOR_LIST__ = .;
> ___CTOR_LIST__ = .;
> LONG (((__CTOR_END__ - __CTOR_LIST__) / 4) - 2)
> KEEP (*(SORT (.ctors.*)))
> KEEP (*(.ctors))
> LONG (0x00000000)
> __CTOR_END__ = .;
> . = ALIGN (0x10);
> 
> __DTOR_LIST__ = .;
> ___DTOR_LIST__ = .;
> LONG (((__DTOR_END__ - __DTOR_LIST__) / 4) - 2)
> KEEP (*(SORT (.dtors.*)))
> KEEP (*(.dtors))
> LONG (0x00000000)
> __DTOR_END__ = .;
> . = ALIGN (0x10);"

gcc=gcc-11.2.0
binutils=binutils-2.37
cmake=cmake-3.22.1
ver=1.2
toolchain=/usr/local/mipsel-unknown-elf
sdk=psn00bsdk

echo "PSnoobSDK Installer By Alex Free v$ver"

dnf=$(command -v dnf)
apt=$(command -v apt)
windows=$(uname)

if echo "$windows" | grep -q "MINGW64"; then
	echo "MSYS2 Windows system detected"
else
	if [ "$EUID" -ne 0 ]; then
		echo "$USER does not have the required privilages to execute "$0", execute sudo "$0""
		exit 1
	fi
fi

cd "$(dirname "$0")"
echo "Cleaning build directory..."
rm -rf build
rm -rf $toolchain
mkdir build

if [ ! -z "$dnf" ]; then
	echo "Detected the DNF file manager, configured to download Fedora dependencies"
    dnf install -y make texinfo mpfr-devel isl-devel gmp-devel libmpc-devel automake gcc gcc-c++ kernel-devel git wget tinyxml2-devel
elif [ ! -z "$apt" ]; then
	echo "Detected the APT file manager, configured to download Debian/Ubuntu dependencies"
    apt install -y texinfo libmpfr-dev libisl-dev libgmp-dev libmpc-dev build-essential git wget libtinyxml2-dev
elif echo "$windows" | grep -q "MINGW64"; then 
	echo "Detected the MSYS2 pacman package manager, configured to download MSYS2 dependencies"
	pacman -S --noconfirm mingw-w64-x86_64-mpfr mingw-w64-x86_64-isl mingw-w64-x86_64-gmp mingw-w64-x86_64-mpc mingw-w64-x86_64-tinyxml2 automake git make wget   texinfo mingw-w64-x86_64-gcc
else
    read -p "Warning: dependencies for this system could not be automatically installed as it does not appear to use the apt, dnf, or msys2 pacman package managers. Continue anyways? (Y/n): " -n 1 -r
echo
        if [ ! $REPLY = "y" ]; then
            if [ ! $REPLY = "Y" ]; then
                exit 1
            fi
		fi
fi

set -e

cp -pr $cmake build
cd build/$cmake
./bootstrap -- -DCMAKE_USE_OPENSSL=OFF
./configure --prefix=$toolchain
make install
cd ../../
rm -rf build/$cmake

cp -pr $binutils build
cd build/$binutils
mkdir binutils-build
cd binutils-build
if echo "$windows" | grep -q "MINGW64"; then 
	../configure --prefix=$toolchain --target=mipsel-unknown-elf --with-float=soft --build=x86_64-w64-mingw32
else
	../configure --prefix=$toolchain --target=mipsel-unknown-elf --with-float=soft
fi
make -j4
make install
cd ../../../
rm -rf build/$binutils

cp -r $gcc build
cd build/$gcc
mkdir gcc-build
cd gcc-build
if echo "$windows" | grep -q "MINGW64"; then 
	../configure --disable-nls --disable-libada --disable-libssp --disable-libquadmath --disable-libstdc++-v3 --target=mipsel-unknown-elf --prefix=/usr/local/mipsel-unknown-elf --with-float=soft --enable-languages=c,c++ --with-gnu-as --with-gnu-ld --build=x86_64-w64-mingw32
else
	../configure --disable-nls --disable-libada --disable-libssp --disable-libquadmath --disable-libstdc++-v3 --target=mipsel-unknown-elf --prefix=/usr/local/mipsel-unknown-elf --with-float=soft --enable-languages=c,c++ --with-gnu-as --with-gnu-ld
fi
make -j4
make install
cd ../../../
rm -rf build/$gcc

cp -pr $sdk build
cd build/$sdk
export PATH=/usr/local/mipsel-unknown-elf/bin:$PATH
cmake --preset default . -G "Unix Makefiles" --install-prefix $toolchain
cmake --build ./build
cmake --install ./build
cd ../../
rm -rf build
echo "$cpp_patch" | patch /usr/local/mipsel-unknown-elf/mipsel-unknown-elf/lib/ldscripts/elf32elmip.x

echo "The $gcc compiler and $binutils tolchain has been installed to /usr/local/mipsel-unknown-elf. The PSn00bSDK is at /usr/local/mipsel-unknown-elf/psn00bsdk, the examples programs distributed with the SDK have been built successfully to test this setup. Run this command to put the SDK/toolchain in your path: export PATH=/usr/local/mipsel-unknown-elf/bin:$PATH"